### PR TITLE
Fix/auto scroll map section

### LINKED ISSUE #120: The auto scroll is not happening on the Map Section scrolling elements
**Describe the bug**
At the Map Section on the home page if the current visualization switches to an element in the list that's not appearing on screen because of the scrolling behavior we want to make the scroll happen automatically to make listed element appears on screen.

**Expected behavior**
We want to make the scroll happen automatically 

**Screenshots**
Here's [a video kind of showing the problem happening](https://www.loom.com/share/f1210ee75d9c4dbebc139393c64fd475)

### PR DESCRIPTION
**Pull request by LeilaFarias**
This PR fixes the bug in the Map Section on the home page, the scroll should happen automatically and follow the current visualization.

### CODE REVIEW

**Review by abraaovalentim — CHANGES_REQUESTED** [review]
I think it would be better for the scroll animation to only happen when the current frame is no longer visible or close to it. I don't know if happening every time we make a change is ideal, I feel as if the animation is breaking a little.

**Review by LazaroQueiroz — CHANGES_REQUESTED** [review]
i think the auto-scroll does not works on mobile... in any of them..

it'd be nice if it worked there too.

**Comment by LeilaFarias** [comment]
I have implemented the requested changes, and now the auto scroll behaves correctly and  also works on mobile devices. Thanks! if you guys could review it again that would be great :)

File: src/components/MapsSection/MapsSection.tsx [hunk 1]
```diff
@@ -102,6 +104,57 @@ const MapsSection = ({
...
+      );
+
+      const containerTop = container.scrollTop;
+      const containerBottom = containerTop + container.clientHeight;
+
+      const buttonOffsetHeight = button.offsetHeight;
+      const buttonHeight = button.offsetTop;
+      +buttonOffsetHeight;
+
+      let tamBotao = buttonHeight / 100;
```
Comment (RodrigoEC) [inline src/components/MapsSection/MapsSection.tsx]: variable in portuguese here

File: src/components/MapsSection/MapsSection.tsx [hunk 2]
```diff
@@ -102,6 +104,57 @@ const MapsSection = ({
...
+      const isMobile = window.innerWidth <= 810;
+      const screen = window.innerHeight;
+      const maxVisibleBoxes = isMobile ? 1 : 5;
+      const needsScroll =
+        (buttonHeight / 9) * currentIndex > containerBottom ||
```
Comment (RodrigoEC) [inline src/components/MapsSection/MapsSection.tsx]: How did you came up with this solution, meaning how do you know it works? Just curious

File: src/components/MapsSection/MapsSection.tsx [hunk 3]
```diff
@@ -102,6 +104,57 @@ const MapsSection = ({
...
+        currentIndex === 0;
+
+      if (needsScroll) {
+        const scrollDesktop = Math.abs(
+          tamBotao + (currentIndex - maxVisibleBoxes) * buttonOffsetHeight,
```
Comment (RodrigoEC) [inline src/components/MapsSection/MapsSection.tsx]: How did you came up with this solution, meaning how do you know it works? Just curious

File: src/components/MapsSection/MapsSection.tsx [hunk 4]
```diff
@@ -102,6 +104,57 @@ const MapsSection = ({
...
+          top: scrollToPositionDesktop,
+          behavior: "smooth",
+        });
+      }
+
+      if (isMobile && needsScroll) {
+        tamBotao = buttonHeight / 10 + buttonOffsetHeight;
+        const scrollMobile = Math.abs(
+          (tamBotao * currentIndex) / (screen / 370),
+        );
```
Comment (RodrigoEC) [inline src/components/MapsSection/MapsSection.tsx]: How did you came up with this solution, meaning how do you know it works? Just curious

**Review by RodrigoEC — CHANGES_REQUESTED** [review]

File: src/components/MapsSection/MapsSection.tsx (hunk 2 above)
Comment (LeilaFarias) [reply src/components/MapsSection/MapsSection.tsx]: Analyzing the values returned by the functions and looking for a pattern that would show me when a button needs scrolling, i mean, when it overflows the container at the moment it is viewed. Basically, **buttonHeight * currentIndex** represents the size of the button multiplied by the number of buttons **behind it** (if it's the first button, currentIndex = 0; if it's the second button, currentIndex = 1 because there is one button behind it). So, if this size is greater than the container's size, it means it has overflowed, in short, **it needs scrolling when the sum of the button sizes exceeds the containerBottom**. Since buttonHeight didn’t return an exactly suitable value, I had to adjust it by dividing by 9, this part involved a bit of trial and error. I  also tried using some other button height functions, but they weren't as effective.

File: src/components/MapsSection/MapsSection.tsx (hunk 1 above)
Comment (LeilaFarias) [reply src/components/MapsSection/MapsSection.tsx]: oh man, sorry for that lol

File: src/components/MapsSection/MapsSection.tsx (hunk 3 above)
Comment (LeilaFarias) [reply src/components/MapsSection/MapsSection.tsx]: Since I couldn’t find a function that would return the exact position of a button relative to the container and considering overflow, I started observing some patterns. The scroll will always happen based on **the size of the button I’m scrolling to** (tamBotao) (tamBotao is different from buttonOffsetHeight because tamBotao considers the size of the open button, while buttonOffsetHeight is the size of the closed button) **+ the number of closed buttons behind it** ((currentIndex - maxVisibleBoxes) * buttonOffsetHeight). The need for maxVisibleBoxes is because it ensures scrolling only considers buttons that aren’t overflowing above the container; without this variable, it would multiply by the total number of buttons behind it, including those overflowing, which would make the calculation incorrect

File: src/components/MapsSection/MapsSection.tsx (hunk 4 above)
Comment (LeilaFarias) [reply src/components/MapsSection/MapsSection.tsx]: Honestly, this was more trial and error. Since I already had scrollDesktop working well, I tried adapting it for mobile using the same variables. I also noticed that the screen height was important for determining the scroll position, so I compared some values until i get screen / 370, which works well for all the tests I did

Comment (LeilaFarias) [reply src/components/MapsSection/MapsSection.tsx]: By the way, I would love to hear your suggestions for improving this part of the code and the previous ones. I honestly believe I did some things that are unnecessary, but I didn’t know how to do better at the time

**Comment by LeilaFarias** [comment]
Hey team, Rodrigo brought up some relevant questions about the scroll, it was using very specific values that may not adapt well to different screen sizes. So, I implemented a better version of the auto scroll, and now it works perfectly on all types of screens and has a better behavior

P.S. Sorry Rodrigo, I couldn't use scrollIntoView() because of that strange issue of scrolling the entire screen along with the div's scroll, but please take a look at this new version :)

**Review by RodrigoEC — APPROVED** [review]
Great work! Loved this solution, is way better and cleaner than the other one, congrats!

image
