### PR TITLE
fix: fixing bottleneck in the carousel images

### LINKED ISSUE #140: Fix bottleneck in the carousel images

### PR DESCRIPTION
**Pull request by LeilaFarias**
This PR aims to fix the bottleneck in the homepage carousel. To achieve this, I tested some ideas and reached this simple conclusion that seems to have solved the issue: 

1. All carousel images are slightly resized (which causes them to lose a bit of quality) 
2. I changed the carousel so that the image being displayed is in maximum quality, while the others have reduced quality.
3. (Bonus) i also changed the 'flowers-background.png' to 'flowers-background.webp', It was something i noticed was affecting performance and was simple to change.

After this changes, Lighthouse stopped flagging the 'properly size images' issue for the carousel images, and the display time of the largest contentful element has been significantly reduced

### lighthouse results on branch "main":
lighthouse before

### lighthouse results on this branch:
lighthouse after

note that it still flags the 'properly size images' issue, however, this now refers to other elements and not the carousel images

### CODE REVIEW

File: src/components/PhotoAlbum/PhotoAlbum.tsx [hunk 1]
```diff
@@ -33,10 +33,11 @@ export const PhotoAlbum = ({ photos }: { photos: any[] }) => {
           distance={Math.abs(currentPhoto - index)}
           onClick={() => setCurrentPhoto(index)}
           active={(index === currentPhoto).toString()}
-          src={`https:${photo.fields.file.url}`}
-          height={300}
-          width={600}
+          src={`https:${photo.fields.file.url}?&w=500`}
```
Comment (RodrigoEC) [inline src/components/PhotoAlbum/PhotoAlbum.tsx]: What this `&w=500` does? if it's the width of the image, i would guess it's not doing much because of the width property given below

File: src/components/PhotoAlbum/PhotoAlbum.tsx [hunk 2]
```diff
@@ -33,10 +33,11 @@ export const PhotoAlbum = ({ photos }: { photos: any[] }) => {
...
+          height={280}
+          width={500}
           alt=""
+          quality={currentPhoto === index ? 100 : 10}
```
Comment (RodrigoEC) [inline src/components/PhotoAlbum/PhotoAlbum.tsx]: Great addition!

What if we also used the [priority](https://nextjs.org/docs/pages/api-reference/components/image#priority) property?

**Review by RodrigoEC — CHANGES_REQUESTED** [review]
Loved the additions, commented a thing that we could maybe also use

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 1 above)
Comment (LeilaFarias) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: it's a query parameter to load the image from the CMS resized to 500px width. Without it, the image would be loaded in its original size and only resized in the browser (that's how i understand it). but if we notice that it doesn't make much difference in performance, we can remove it :)

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 2 above)
Comment (LeilaFarias) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: do you mean, use it the same way we use the quality property? Very interesting, i can test that

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 1 above)
Comment (LazaroQueiroz) [inline src/components/PhotoAlbum/PhotoAlbum.tsx]:
```suggestion
          src={`https:${photo.fields.file.url}?&w=624&h=448`}
```

Comment (LazaroQueiroz) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: i think this change would make the quality of the image a little bit better without affecting significantly the site's performance.

File: src/components/PhotoAlbum/PhotoAlbum.tsx [hunk 3]
```diff
@@ -33,10 +33,11 @@ export const PhotoAlbum = ({ photos }: { photos: any[] }) => {
           distance={Math.abs(currentPhoto - index)}
           onClick={() => setCurrentPhoto(index)}
           active={(index === currentPhoto).toString()}
-          src={`https:${photo.fields.file.url}`}
-          height={300}
-          width={600}
+          src={`https:${photo.fields.file.url}?&w=500`}
+          height={280}
+          width={500}
```
Comment (LazaroQueiroz) [inline src/components/PhotoAlbum/PhotoAlbum.tsx]:
```suggestion
          height={272}
          width={416}
```

Comment (LazaroQueiroz) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: i think this would be more coherent with the image's display size.

**Review by LazaroQueiroz — CHANGES_REQUESTED** [review]
Very nice work!! really improved the site's performance!
just some minor comments about the code...
really nice work!! congrats!

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 2 above)
Comment (LazaroQueiroz) [inline src/components/PhotoAlbum/PhotoAlbum.tsx]:
```suggestion
          quality={currentPhoto === index ? 100 : 5}
```

Comment (LazaroQueiroz) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: i think this even smaller resolution would compensate the higher image quality.

**Review by LazaroQueiroz — CHANGES_REQUESTED** [review]

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 2 above)
Comment (RodrigoEC) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: Exactly!

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 1 above)
Comment (RodrigoEC) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: Got it. I think you could change it to what Lazaro pointed - with the height param also

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 3 above)
Comment (LeilaFarias) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: i noticed in the Lighthouse measurements that the parameters in this format were causing a slight "cumulative layout shift", so i choose to set **height={448} width={624}** as i think it aligns better with the image size, do you agree?

File: src/components/PhotoAlbum/PhotoAlbum.tsx (hunk 1 above)
Comment (LeilaFarias) [reply src/components/PhotoAlbum/PhotoAlbum.tsx]: nice suggestion!! thanks

**Review by RodrigoEC — APPROVED** [review]
